"""Constants for inventory app."""

USER_ACTION_STATUS_CREATED = 'CREATED'
USER_ACTION_STATUS_UPDATED = 'UPDATED'
USER_ACTION_STATUS_DELETED = 'DELETED'

USER_ACTION_STATUS_CHOICES = (
    (USER_ACTION_STATUS_CREATED, 'Created'),
    (USER_ACTION_STATUS_UPDATED, 'Updated'),
    (USER_ACTION_STATUS_DELETED, 'Deleted'))

DEFAULT_LIMIT = 20
DEFAULT_OFFSET = 0
